# Top-level settings (common to all projects)
[GLOBAL]
NGSPICE_EXE_STR = "/usr/bin/ngspice"
NETLISTS_DIR_STR = "netlists"             # relative to proj dir, where netlists will be stored
RESULTS_DIR_STR = "sim_results"           # rel to proj dir, where sim results will be stored
SIM_TRANSCRIPT_STR = "sim_transcript.log" # filename for ngspice simulation transcripts


# Section 1-04-04 Linear Regulator
[SEC_1_04_04]
PROJ_PATH_STR = "/workspaces/example_py4spice_01/circuits/sec_1_04_04_lin_reg"
